# Generated by Django 4.2.6 on 2023-10-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, auto_created=True)),
                ('nome', models.CharField(max_length=100, unique=True, null=False)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
