# Generated by Django 4.2.6 on 2023-10-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ok',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
