# Generated by Django 4.2.6 on 2023-11-01 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_estoque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='ID_Produto',
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.PROTECT, to='myapp.estoque'),
            preserve_default=False,
        ),
    ]
