# Generated by Django 4.2.6 on 2023-11-01 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_estoque_id_produto_produto_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estoques', to='myapp.estoque'),
        ),
    ]
