# Generated by Django 4.2.8 on 2024-01-06 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_produto_ok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estoques', to='myapp.estoque'),
        ),
    ]
